version: '3.1'

services:
  mongo:
    image: mongo:latest
    restart: always
    ports:
      - 27018:27017
    environment:
      MONGO_INITDB_ROOT_DATABASE: equipmentTracking
    volumes:
      - db:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: 12345

  equipment_tracking:
    restart: unless-stopped
    build: .
    ports:
      - '8000:8000'
    depends_on:
      - mongo
    environment:
      - MONGO_DB_URL=mongodb://mongo:27017
      - MONGO_DATABASE_NAME=equipmentTracking
      - PORT=8000

volumes:
  db:
